set -s default-terminal 'tmux-256color'
set -s escape-time 0
set -s focus-events on
set -as terminal-features "${TERM}:RGB"

set -g base-index 1
set -g default-shell '/usr/bin/fish'
set -g display-time 2000
set -g history-limit 50000
set -g mouse on
set -g renumber-windows on

set -gw aggressive-resize on
set -gw mode-keys vi
set -gw pane-base-index 1

source-file "~/.local/share/nvim/site/pack/core/opt/tokyonight.nvim/extras/tmux/tokyonight_storm.tmux"

unbind %
unbind '"'
bind v split-window -v -c '#{pane_current_path}'
bind b split-window -h -c '#{pane_current_path}'
bind c new-window -c '#{pane_current_path}'

bind x kill-pane

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
