command_timeout = 1000
scan_timeout = 1000
format = '$python$all$line_break$character'
right_format = '$time'

[c]
disabled = true

[cmd_duration]
disabled = true

[directory]
truncate_to_repo = false
truncation_length = 0

[git_branch]
format = '[$branch ]($style)'

[git_status]
disabled = true

[python]
format = '[${pyenv_prefix}(\($virtualenv\) )]($style)'
style = 'bold blue'

[status]
disabled = false
format = '[$status]($style)'

[time]
disabled = false
format = '[$time]($style)'

[username]
format = '[$user ]($style)'
style_user = 'bold green'
